Repository chococookie-lol/BARAM, pull requests merged in 2022-12, with the labels that each got.

#2 FE 환경설정
  .prettierrc.js
  client/.eslintrc.json
  client/.gitignore
  client/next.config.js
  client/package.json
  client/pages/_app.tsx
  client/pages/_document.tsx
  client/pages/index.tsx
  client/public/favicon.ico
  client/styles/globals.css
  client/tsconfig.json
  client/yarn.lock
Labels: FE

#6 fix: eslint 오류 수정 (Close #5)
  client/.eslintrc.json
Labels: FE

#4 deploy 스크립트 작성
  deploy-client.sh
  deploy.sh
Labels: FE

#7 2022.12.23 작업사항
  .prettierrc.js
  client/.eslintrc.json
  client/.gitignore
  client/next.config.js
  client/package.json
  client/pages/_app.tsx
  client/pages/_document.tsx
  client/pages/index.tsx
  client/public/favicon.ico
  client/styles/globals.css
  client/tsconfig.json
  client/yarn.lock
  deploy-client.sh
  deploy.sh
Labels: FE

#8 fix: deploy 스크립트 오류 수정
  deploy-client.sh
Labels: FE

#9 hotfix: deploy 스크립트 수정
  deploy-client.sh
Labels: FE

#11 BE 환경설정
  deploy-server.sh
  deploy.sh
  server/.eslintrc.js
  server/.gitignore
  server/nest-cli.json
  server/package.json
  server/src/app.module.ts
  server/src/main.ts
  server/test/app.e2e-spec.ts
  server/test/jest-e2e.json
  server/tsconfig.build.json
  server/tsconfig.json
  server/yarn.lock
Labels: BE

#12 BE 환경설정
  deploy-server.sh
  deploy.sh
  server/.eslintrc.js
  server/.gitignore
  server/nest-cli.json
  server/package.json
  server/src/app.module.ts
  server/src/main.ts
  server/test/app.e2e-spec.ts
  server/test/jest-e2e.json
  server/tsconfig.build.json
  server/tsconfig.json
  server/yarn.lock
Labels: BE

#13 hotfix: deploy-server.sh 실행권한 추가
  deploy-server.sh
Labels: BE

#15 Dummy Api 만들기
  server/package.json
  server/src/app.module.ts
  server/src/main.ts
  server/src/matches/dtos/get-matchId.dto.ts
  server/src/matches/matches.controller.spec.ts
  server/src/matches/matches.controller.ts
  server/src/matches/matches.module.ts
  server/src/matches/matches.service.spec.ts
  server/src/matches/matches.service.ts
  server/src/summoners/dtos/post-matches.dto.ts
  server/src/summoners/summoners.controller.spec.ts
  server/src/summoners/summoners.controller.ts
  server/src/summoners/summoners.module.ts
  server/src/summoners/summoners.service.spec.ts
  server/src/summoners/summoners.service.ts
  server/yarn.lock
Labels: BE

#16 Dummy api 만들기
  server/package.json
  server/src/app.module.ts
  server/src/main.ts
  server/src/matches/dtos/get-matchId.dto.ts
  server/src/matches/matches.controller.spec.ts
  server/src/matches/matches.controller.ts
  server/src/matches/matches.module.ts
  server/src/matches/matches.service.spec.ts
  server/src/matches/matches.service.ts
  server/src/summoners/dtos/post-matches.dto.ts
  server/src/summoners/summoners.controller.spec.ts
  server/src/summoners/summoners.controller.ts
  server/src/summoners/summoners.module.ts
  server/src/summoners/summoners.service.spec.ts
  server/src/summoners/summoners.service.ts
  server/yarn.lock
Labels: BE

#19 FE 전역 테마 설정
  client/.eslintrc.json
  client/next.config.js
  client/package.json
  client/pages/_app.tsx
  client/styles/GlobalThemeContext.tsx
  client/styles/theme.ts
  client/tsconfig.json
  client/yarn.lock
Labels: FE

#22 FE 로고 구현
  client/assets/logo.svg
  client/components/Logo/index.tsx
  client/next.config.js
  client/package.json
  client/yarn.lock
Labels: FE

#24 FE 챔피언 초상화 구현
  client/components/ChampionPic/index.tsx
  client/next.config.js
Labels: FE

#28 전적 버튼 구현 (Close #27)
  client/components/Button/index.tsx
Labels: FE

#30 FE 퍼센트 바 구현
  client/components/Percentage/index.tsx
  client/components/Percentage/style.ts
Labels: FE

#31 FE Pie chart 구현
  client/components/Doughnut/index.tsx
  client/components/Doughnut/pathHelper.ts
  client/components/Doughnut/style.ts
Labels: FE

#33 2022.12.29 작업사항
  client/.env.development
  client/.env.production
  client/.eslintrc.json
  client/assets/logo.svg
  client/assets/search.svg
  client/components/Button/index.tsx
  client/components/ChampionPic/index.tsx
  client/components/Doughnut/index.tsx
  client/components/Doughnut/pathHelper.ts
  client/components/Doughnut/style.ts
  client/components/Logo/index.tsx
  client/components/Percentage/index.tsx
  client/components/Percentage/style.ts
  client/components/SearchBar/index.tsx
  client/components/SearchBar/style.ts
  client/next.config.js
  client/package.json
  client/pages/_app.tsx
  client/styles/GlobalThemeContext.tsx
  client/styles/theme.ts
  client/tsconfig.json
  client/yarn.lock
Labels: FE

#38 Eslint 설정 오류 수정 및 서버 테스트 수정 (Close #37)
  client/.eslintrc.json
  server/src/matches/matches.controller.spec.ts
  server/src/summoners/summoners.controller.spec.ts
Labels: bug
