Repository chococookie-lol/BARAM, pull requests merged in 2023-01, with the labels that each got.

#45 메인 페이지 구성
  client/pages/index.tsx
  client/styles/globals.css
Labels: FE

#47 hotfix: theme 수정 (Close #46)
  client/styles/theme.ts
Labels: Hotfix

#48 feat: 퍼센트 통계 컴포넌트 작성 (Close #43)
  client/components/Percentage/index.tsx
  client/components/PercentageStatistics/index.tsx
  client/components/PercentageStatistics/style.ts
Labels: FE

#52 FE SummonerProfilePic 구현
  client/components/SummonerProfilePic/index.tsx
Labels: FE

#50 FE RelativeBar 구현
  client/components/RelativeBar/index.tsx
  client/components/RelativeBar/style.ts
Labels: FE

#54 FE Challenges 컴포넌트 구현
  client/components/ChallengeIcon/index.tsx
Labels: FE

#57 2023.01.02 작업사항
  .gitignore
  client/assets/logo.svg
  client/components/ChallengeIcon/index.tsx
  client/components/Logo/index.tsx
  client/components/Percentage/index.tsx
  client/components/PercentageStatistics/index.tsx
  client/components/PercentageStatistics/style.ts
  client/components/RelativeBar/index.tsx
  client/components/RelativeBar/style.ts
  client/components/SearchBar/style.ts
  client/components/SummonerProfilePic/index.tsx
  client/pages/index.tsx
  client/styles/globals.css
  client/styles/theme.ts
Labels: FE, Chore

#63 Global theme 색 추가
  client/styles/theme.ts
Labels: FE

#64 feat: PercentageStatistics 색상 옵션 추가
  client/components/PercentageStatistics/index.tsx
  client/components/PercentageStatistics/style.ts
Labels: FE

#59 feat: Doughnut 색 옵션 추가
  client/components/Doughnut/index.tsx
  client/components/Doughnut/style.ts
Labels: FE

#68 ItemIcon 구현
  client/components/ItemIcon/index.tsx
Labels: FE

#65 소환사 통계 컴포넌트 작성
  client/components/SummonerStatCard/index.tsx
  client/components/SummonerStatCard/style.ts
Labels: FE

#70 FE ItemStrip 구현
  client/components/ItemStrip/index.tsx
Labels: FE

#72 fix: Global theme 오타 수정
  client/styles/theme.ts
Labels: FE

#74 FE Spell component 구현
  client/components/SpellIcon/index.tsx
  client/components/SpellStrip/index.tsx
Labels: FE

#71 소환사 정보 카드 컴포넌트 작성
  client/components/Button/index.tsx
  client/components/SummonerProfileCard/index.tsx
  client/components/SummonerProfileCard/style.ts
Labels: FE

#76 FE Rune 구현
  client/components/RuneIcon/index.tsx
  client/components/RuneIcon/style.ts
Labels: FE

#77 2023.01.04 작업사항
  client/components/Button/index.tsx
  client/components/Doughnut/index.tsx
  client/components/Doughnut/style.ts
  client/components/ItemIcon/index.tsx
  client/components/ItemStrip/index.tsx
  client/components/PercentageStatistics/index.tsx
  client/components/PercentageStatistics/style.ts
  client/components/RuneIcon/index.tsx
  client/components/RuneIcon/style.ts
  client/components/SpellIcon/index.tsx
  client/components/SpellStrip/index.tsx
  client/components/SummonerProfileCard/index.tsx
  client/components/SummonerProfileCard/style.ts
  client/components/SummonerStatCard/index.tsx
  client/components/SummonerStatCard/style.ts
  client/styles/theme.ts
Labels: FE

#81 feat: 전역 색상 추가
  client/styles/theme.ts
  client/utils/color.ts
Labels: FE

#87 PercentageStatistics 레이아웃 수정
  client/components/PercentageStatistics/index.tsx
  client/components/PercentageStatistics/style.ts
Labels: FE

#90 build: global.d.ts 추가
  client/global.d.ts
  client/tsconfig.json
Labels: FE

#91 fix: Challenge 인터페이스 수정
  client/components/SummonerProfileCard/index.tsx
  client/global.d.ts
Labels: FE

#95 검색 페이지 구현
  client/global.d.ts
  client/package.json
  client/pages/summoners/[summonerName].tsx
  client/utils/api.ts
  client/yarn.lock
Labels: FE

#108 feat: 페이지 min width 설정
  client/styles/globals.css
Labels: FE

#109 feat: 상대 시간 표시
  client/components/SummonerProfileCard/index.tsx
  client/utils/time.ts
Labels: FE

#111 feat: dev, prod api 주소 통일
  client/.env.development
  client/next.config.js
Labels: FE

#112 검색 페이지에 GameSlot 추가 및 ERD 수정 반영
  client/global.d.ts
  client/pages/summoners/[summonerName].tsx
  server/src/summoners/summoners.service.ts
Labels: FE, BE

#115 ddragon api component에 적용
  client/components/ChallengeIcon/index.tsx
  client/components/ChampionPic/index.tsx
  client/components/GameSlot/helper.ts
  client/components/GameSlot/index.tsx
  client/components/ItemIcon/index.tsx
  client/components/ItemStrip/index.tsx
  client/components/RuneIcon/index.tsx
  client/components/SpellIcon/index.tsx
  client/components/SpellStrip/index.tsx
  client/components/SummonerProfileCard/index.tsx
  client/components/SummonerProfilePic/index.tsx
  client/utils/ddragon.ts
Labels: FE

#117 2023.01.06 작업사항
  client/.env.development
  client/components/ChallengeIcon/index.tsx
  client/components/ChampionPic/index.tsx
  client/components/GameSlot/helper.ts
  client/components/GameSlot/index.tsx
  client/components/ItemIcon/index.tsx
  client/components/ItemStrip/index.tsx
  client/components/RuneIcon/index.tsx
  client/components/SpellIcon/index.tsx
  client/components/SpellStrip/index.tsx
  client/components/SummonerProfileCard/index.tsx
  client/components/SummonerProfilePic/index.tsx
  client/global.d.ts
  client/next.config.js
  client/package.json
  client/pages/_app.tsx
  client/pages/summoners/[summonerName].tsx
  client/states/ddragon.ts
  client/styles/globals.css
  client/utils/ddragon.ts
  client/utils/time.ts
  client/yarn.lock
  server/src/summoners/summoners.service.ts
Labels: FE

#119 FE Percentage, PercentageStatistics 수정
  client/components/Percentage/index.tsx
  client/components/Percentage/style.ts
  client/components/PercentageStatistics/style.ts
Labels: FE

#120 FE Doughnut 수정
  client/components/Doughnut/pathHelper.ts
  client/components/Doughnut/style.ts
Labels: FE

#122 FE 소환사 통계 데이터 집계 및 API 수정
  client/components/SummonerStatCard/index.tsx
  client/global.d.ts
  client/pages/summoners/[summonerName].tsx
  client/utils/matchStatistic.ts
  server/src/matches/matches.service.ts
Labels: FE, BE

#126 feat: matches contribution 수정
  client/global.d.ts
  server/src/matches/matches.service.ts
Labels: BE

#127 2023.01.09 작업사항
  client/components/Doughnut/pathHelper.ts
  client/components/Doughnut/style.ts
  client/components/Percentage/index.tsx
  client/components/Percentage/style.ts
  client/components/PercentageStatistics/style.ts
  client/components/SummonerStatCard/index.tsx
  client/global.d.ts
  client/pages/summoners/[summonerName].tsx
  client/utils/matchStatistic.ts
  server/src/matches/matches.service.ts
Labels: FE, BE

#133 fix: GameSlot 힐, 탱 기준 변경
  client/components/GameSlot/helper.ts
  client/components/GameSlot/index.tsx
  client/utils/time.ts
Labels: Bug, FE

#132 fix: SummonerStatCard 내부 선택 불가 (Close #131)
  client/components/SummonerStatCard/style.ts
Labels: Bug, FE

#130 fix: SummonerProfileCard 높이 2px 증가
  client/components/SummonerProfileCard/style.ts
Labels: Bug, FE

#129 fix: SummonerStatCard의 PercentageStat 패딩 추가
  client/components/SummonerStatCard/index.tsx
Labels: Bug, FE

#128 fix: RelativeBar 최소값 지정 (Close #125)
  client/components/RelativeBar/index.tsx
Labels: Bug, FE

#135 2023.01.10 작업사항
  client/components/GameSlot/helper.ts
  client/components/GameSlot/index.tsx
  client/components/RelativeBar/index.tsx
  client/components/SummonerProfileCard/style.ts
  client/components/SummonerStatCard/index.tsx
  client/components/SummonerStatCard/style.ts
  client/utils/time.ts
Labels: Bug, FE

#140 Riot API 모듈 작성
  server/package.json
  server/src/app.module.ts
  server/src/matches/matches.controller.spec.ts
  server/src/matches/matches.service.spec.ts
  server/src/riot.api/interface/index.ts
  server/src/riot.api/interface/riot.summoner.interface.ts
  server/src/riot.api/riot.api.module.ts
  server/src/riot.api/riot.api.service.ts
  server/src/summoners/summoners.controller.spec.ts
  server/src/summoners/summoners.service.spec.ts
  server/test/app.e2e-spec.ts
  server/yarn.lock
Labels: BE, Chore

#143 Summoner API 구현
  server/src/riot.api/interface/index.ts
  server/src/riot.api/interface/riot.challenge.interface.ts
  server/src/riot.api/riot.api.service.ts
  server/src/summoners/schemas/summoner.schema.ts
  server/src/summoners/summoners.controller.ts
  server/src/summoners/summoners.module.ts
  server/src/summoners/summoners.service.ts
Labels: BE, Refactor

#146 FE 버그 및 console.log 제거
  client/pages/summoners/[summonerName].tsx
  client/utils/matchStatistic.ts
Labels: Bug, FE, Refactor

#150 feat: match participation 추가
  client/global.d.ts
  server/src/matches/matches.service.ts
Labels: BE

#152 GameSlot expand 구현
  .gitignore
  client/components/GameSlot/index.tsx
  client/components/GameSlot/style.ts
  client/components/GameSlotDetail/index.tsx
  client/components/GameSlotDetail/style.ts
  client/components/ItemStrip/index.tsx
Labels: FE, Refactor, Chore

#157 소환사 API 수정 및 리팩토링
  server/src/riot.api/definition/riot.api.exception.ts
  server/src/riot.api/riot.api.service.ts
  server/src/summoners/summoners.service.ts
Labels: Bug, BE, Refactor

#164 fix: FE 기여도 직접 계산 제거
  client/components/GameSlot/index.tsx
  client/utils/matchStatistic.ts
Labels: Bug, FE

#159 feat: PercentageBar 구현
  client/components/GameSlotDetail/index.tsx
  client/components/PercentageBar/index.tsx
Labels: FE

#160 fix: 최근 업데이트 날짜 표시 오류 수정
  client/components/SummonerProfileCard/index.tsx
  client/global.d.ts
  client/pages/summoners/[summonerName].tsx
Labels: Bug, FE

#161 BE matches api 구현
  server/src/matches/matches.controller.ts
  server/src/matches/matches.module.ts
  server/src/matches/matches.service.ts
  server/src/matches/schemas/match.schema.ts
  server/src/riot.api/interface/riot.match.interface.ts
  server/src/riot.api/riot.api.service.ts
  server/src/summoners/summoners.service.ts
Labels: BE, Chore

#166 GameSlot 수정
  client/components/GameSlot/index.tsx
  client/components/GameSlot/style.ts
  client/components/GameSlotDetail/index.tsx
  client/components/GameSlotDetail/style.ts
Labels: Bug, FE, Refactor

#169 2023.01.13 작업사항
  client/components/GameSlot/index.tsx
  client/components/GameSlot/style.ts
  client/components/GameSlotDetail/index.tsx
  client/components/GameSlotDetail/style.ts
  client/global.d.ts
  client/pages/summoners/[summonerName].tsx
  client/utils/api.ts
  client/utils/matchStatistic.ts
  server/src/matches/dtos/get-puuid.dto.ts
  server/src/matches/dtos/post-puuid.dto.ts
  server/src/matches/matches.controller.ts
  server/src/matches/matches.service.ts
  server/src/matches/schemas/match.schema.ts
  server/src/riot.api/interface/riot.match.interface.ts
  server/src/riot.api/riot.api.service.ts
Labels: FE, BE, Refactor

#174 BE schema 수정
  server/src/matches/matches.service.ts
  server/src/matches/schemas/match.schema.ts
Labels: Bug, BE

#177 RiotAPI, 소환사 검색 오류 해결
  client/pages/summoners/[summonerName].tsx
  server/src/riot.api/riot.api.service.ts
Labels: Bug, FE, BE

#178 fix: ddragon 기본 이미지 추가
  client/utils/ddragon.ts
Labels: Bug, FE

#181 fix: 최소값이 50 넘어가지 않도록 수정 (Close #171)
  client/components/RelativeBar/index.tsx
Labels: Bug, FE

#180 BE match fetch시 polling 하도록 api 수정
  client/global.d.ts
  server/src/matches/matches.module.ts
  server/src/matches/matches.service.ts
  server/src/summoners/schemas/summoner.schema.ts
Labels: BE

#182 Play 추가 및 Match 정렬
  server/src/app.module.ts
  server/src/matches/dtos/post-puuid.dto.ts
  server/src/matches/matches.controller.ts
  server/src/matches/matches.module.ts
  server/src/matches/matches.service.ts
  server/src/play/play.module.ts
  server/src/play/play.service.ts
  server/src/play/schemas/play.schema.ts
Labels: BE

#185 라이선스 추가
  LICENSE
Labels: Chore

#186 2023.01.17 작업사항
  LICENSE
  client/components/RelativeBar/index.tsx
  client/global.d.ts
  client/pages/summoners/[summonerName].tsx
  client/utils/ddragon.ts
  server/src/app.module.ts
  server/src/matches/dtos/post-puuid.dto.ts
  server/src/matches/matches.controller.ts
  server/src/matches/matches.module.ts
  server/src/matches/matches.service.ts
  server/src/matches/schemas/match.schema.ts
  server/src/play/play.module.ts
  server/src/play/play.service.ts
  server/src/play/schemas/play.schema.ts
  server/src/riot.api/riot.api.service.ts
  server/src/summoners/schemas/summoner.schema.ts
Labels: Bug, FE, BE, Chore

#188 hotfix: #187
  server/src/matches/matches.controller.ts
Labels: BE, Hotfix

#191 feat: ddragon 버전 관리 (Close #189)
  client/components/GameSlot/index.tsx
  client/components/ItemIcon/index.tsx
  client/components/ItemStrip/index.tsx
  client/components/RuneIcon/index.tsx
  client/components/SpellIcon/index.tsx
  client/components/SpellStrip/index.tsx
  client/states/ddragon.ts
  client/utils/ddragon.ts
Labels: FE

#192 FE /summoners/:summonerName api 적용
  client/components/Button/index.tsx
  client/components/SummonerProfileCard/index.tsx
  client/global.d.ts
  client/pages/summoners/[summonerName].tsx
  client/utils/api.ts
  client/utils/matchStatistic.ts
Labels: FE, Refactor

#193 2023.01.17 작업사항
  client/components/Button/index.tsx
  client/components/GameSlot/index.tsx
  client/components/ItemIcon/index.tsx
  client/components/ItemStrip/index.tsx
  client/components/RuneIcon/index.tsx
  client/components/SpellIcon/index.tsx
  client/components/SpellStrip/index.tsx
  client/components/SummonerProfileCard/index.tsx
  client/global.d.ts
  client/pages/summoners/[summonerName].tsx
  client/states/ddragon.ts
  client/utils/api.ts
  client/utils/ddragon.ts
  client/utils/matchStatistic.ts
Labels: FE

#197 fix: play 정렬 게임 생성 시간 기준으로 변경 (Close #195)
  server/src/matches/matches.service.ts
  server/src/play/play.service.ts
  server/src/play/schemas/play.schema.ts
Labels: Bug, BE

#199 fix: GameSlot 아이템 버그 수정 (Close #198)
  client/components/GameSlot/index.tsx
Labels: Bug, FE

#203 fix: FE GameSlot nth-child 대체 (Close #190)
  client/components/GameSlot/index.tsx
  client/components/GameSlot/style.ts
Labels: Bug, FE

#201 FE 펼치는 화살표 추가
  client/assets/downArrow.svg
  client/components/GameSlot/index.tsx
  client/components/GameSlot/style.ts
Labels: FE

#206 첫 검색 시 더보기 버튼 보이지 않도록 수정
  client/pages/summoners/[summonerName].tsx
Labels: Bug, FE

#208 fix: percentageBar 마우스 이벤트
  client/components/PercentageBar/index.tsx
Labels: Bug, FE

#210 2023.01.18 작업사항
  client/assets/downArrow.svg
  client/components/Doughnut/index.tsx
  client/components/Doughnut/pathHelper.ts
  client/components/Doughnut/style.ts
  client/components/GameSlot/index.tsx
  client/components/GameSlot/style.ts
  client/components/Percentage/index.tsx
  client/components/PercentageBar/index.tsx
  client/components/SummonerStatCard/index.tsx
  client/components/SummonerStatCard/style.ts
  client/pages/summoners/[summonerName].tsx
  client/utils/matchStatistic.ts
  server/src/matches/matches.service.ts
  server/src/play/play.service.ts
  server/src/play/schemas/play.schema.ts
Labels: Bug, FE, BE

#212 fix: 챌린지 preference 없는 경우 처리 (Close #209)
  server/src/riot.api/interface/riot.challenge.interface.ts
  server/src/summoners/summoners.service.ts
Labels: Bug, BE

#213 fix: 챔피언 이름과 이미지 이름이 다른 경우 처리 (Close #205)
  client/components/ChampionPic/index.tsx
  client/components/GameSlot/index.tsx
  client/states/ddragon.ts
Labels: Bug, FE

#215 ContributionRank 구현
  client/components/SummonerStatCard/index.tsx
  client/global.d.ts
  client/pages/summoners/[summonerName].tsx
  client/utils/matchStatistic.ts
  server/src/matches/matches.service.ts
  server/src/matches/schemas/match.schema.ts
Labels: FE, BE

#219 fix: FE itemIcon의 기본값을 DEFAULT_PLACEHOLDER로 변경
  client/components/ItemIcon/index.tsx
  client/components/ItemStrip/index.tsx
  client/utils/ddragon.ts
Labels: Bug, FE

#217 BE match service death
  server/src/matches/matches.service.ts
Labels: Bug, BE

#220 2023.01.19 작업사항
  client/components/ChampionPic/index.tsx
  client/components/GameSlot/index.tsx
  client/components/ItemIcon/index.tsx
  client/components/ItemStrip/index.tsx
  client/components/SummonerStatCard/index.tsx
  client/global.d.ts
  client/pages/summoners/[summonerName].tsx
  client/states/ddragon.ts
  client/utils/ddragon.ts
  client/utils/matchStatistic.ts
  server/src/matches/matches.service.ts
  server/src/matches/schemas/match.schema.ts
  server/src/riot.api/interface/riot.challenge.interface.ts
  server/src/summoners/summoners.service.ts
Labels: FE, BE

#223 FE GameSlotTable 수정
  client/components/GameSlot/index.tsx
  client/components/GameSlot/style.ts
Labels: Bug, FE

#225 feat: 날짜 표시 (Close #221)
  client/components/GameSlot/index.tsx
  client/utils/time.ts
Labels: FE

#224 feat: font 적용
  client/pages/_document.tsx
  client/styles/globals.css
Labels: FE

#233 2023.01.20 작업사항
  client/components/GameSlot/index.tsx
  client/components/GameSlot/style.ts
  client/pages/_document.tsx
  client/styles/globals.css
  client/utils/time.ts
Labels: FE, BE

#232 기여도 순위 수정
  client/components/GameSlot/index.tsx
  client/components/GameSlot/style.ts
  client/components/SummonerStatCard/index.tsx
  client/global.d.ts
  client/pages/summoners/[summonerName].tsx
  client/utils/api.ts
  client/utils/matchStatistic.ts
  server/src/app.module.ts
  server/src/matches/matches.service.ts
  server/src/matches/schemas/match.schema.ts
  server/src/statistics/statistics.controller.ts
  server/src/statistics/statistics.module.ts
  server/src/statistics/statistics.service.ts
Labels: FE, BE

#235 fix: 평균 게임 기여도 순위 precision 고정 (Close #228)
  client/components/SummonerStatCard/index.tsx
Labels: Bug, FE

#236 refactor: await, 함수, 순서, 파일명
  client/components/ChallengeIcon/index.tsx
  client/components/ChampionPic/index.tsx
  client/components/Doughnut/index.tsx
  client/components/Doughnut/path.ts
  client/components/GameSlot/index.tsx
  client/components/ItemIcon/index.tsx
  client/components/ItemStrip/index.tsx
  client/components/Logo/index.tsx
  client/components/PercentageStatistics/index.tsx
  client/components/RelativeBar/index.tsx
  client/components/RelativeStatistics/index.tsx
  client/components/RuneIcon/index.tsx
  client/components/SpellIcon/index.tsx
  client/components/SpellStrip/index.tsx
  client/components/SummonerProfilePic/index.tsx
  client/components/SummonerStatCard/index.tsx
  client/pages/summoners/[summonerName].tsx
  client/states/ddragon.ts
  client/utils/api.ts
  client/utils/ddragon.ts
Labels: FE, Refactor

#239 Refactor/#237
  client/.eslintrc.json
  client/components/ChampionPic/index.tsx
  client/components/GameSlot/index.tsx
  client/components/ItemIcon/index.tsx
  client/components/ItemStrip/index.tsx
  client/components/RuneIcon/index.tsx
  client/components/SpellIcon/index.tsx
  client/components/SummonerProfileCard/index.tsx
  client/global.d.ts
  client/next.config.js
  client/package.json
  client/states/ddragon.ts
  client/utils/api.ts
  client/utils/ddragon.ts
  client/yarn.lock
  server/src/matches/matches.module.ts
Labels: FE, Refactor

#241 2023.01.25 작업사항
  client/.eslintrc.json
  client/components/ChallengeIcon/index.tsx
  client/components/ChampionPic/index.tsx
  client/components/Doughnut/index.tsx
  client/components/Doughnut/path.ts
  client/components/GameSlot/index.tsx
  client/components/GameSlot/style.ts
  client/components/ItemIcon/index.tsx
  client/components/ItemStrip/index.tsx
  client/components/Logo/index.tsx
  client/components/PercentageStatistics/index.tsx
  client/components/RelativeBar/index.tsx
  client/components/RelativeStatistics/index.tsx
  client/components/RuneIcon/index.tsx
  client/components/SpellIcon/index.tsx
  client/components/SpellStrip/index.tsx
  client/components/SummonerProfileCard/index.tsx
  client/components/SummonerProfilePic/index.tsx
  client/components/SummonerStatCard/index.tsx
  client/global.d.ts
  client/next.config.js
  client/package.json
  client/pages/summoners/[summonerName].tsx
  client/states/ddragon.ts
  client/utils/api.ts
  client/utils/ddragon.ts
  client/utils/matchStatistic.ts
  client/yarn.lock
  server/src/app.module.ts
  server/src/matches/matches.module.ts
  server/src/matches/matches.service.ts
  server/src/matches/schemas/match.schema.ts
  server/src/statistics/statistics.controller.ts
  server/src/statistics/statistics.module.ts
  server/src/statistics/statistics.service.ts
Labels: FE, BE, Refactor

#244 소환사 테스트 작성
  server/src/summoners/summoners.controller.ts
  server/src/summoners/summoners.service.ts
  server/src/summoners/test/summoners.controller.spec.ts
  server/src/summoners/test/summoners.mock.ts
  server/src/summoners/test/summoners.service.spec.ts
Labels: BE, Refactor, Chore

#247 Matches test 작성
  server/src/matches/matches.module.ts
  server/src/matches/matches.service.ts
  server/src/matches/schemas/match.schema.ts
  server/src/matches/test/matches.controller.spec.ts
  server/src/matches/test/matches.mock.ts
  server/src/matches/test/matches.service.spec.ts
  server/src/riot.api/interface/riot.match.interface.ts
Labels: Bug, BE
