Repository chococookie-lol/BARAM, pull requests merged in 2023-02, with the labels that each got.

#251 fix: FE 소환사가 없을 때 처리 (Close #211)
  client/pages/summoners/[summonerName].tsx
Labels: Bug, FE

#252 대소문자 구분 없이 검색 가능하도록 수정 (Close #250)
  client/global.d.ts
  client/pages/summoners/[summonerName].tsx
  server/src/matches/matches.service.ts
  server/src/summoners/summoners.service.ts
Labels: FE, BE

#253 feat: 최대 퍼센트 옵션 추가
  client/components/Percentage/index.tsx
Labels: FE
