Repository chococookie-lol/BARAM, pull requests merged in 2023-03, with the labels that each got.

#256 더보기 응답이 403일 경우 처리
  client/pages/summoners/[summonerName].tsx
Labels: FE

#259 통계 계산시 total이 0인 경우 처리
  client/utils/matchStatistic.ts
  server/src/matches/matches.service.ts
  server/src/matches/schemas/match.schema.ts
  server/src/play/schemas/play.schema.ts
Labels: Bug, FE, BE

#255 Polling 방식 변경
  client/global.d.ts
  client/pages/summoners/[summonerName].tsx
  client/utils/api.ts
  server/src/matches/matches.service.ts
  server/src/matches/test/matches.service.spec.ts
  server/src/summoners/schemas/summoner.schema.ts
  server/src/summoners/test/summoners.mock.ts
Labels: FE, BE

#261 경기의 딜 혹은 탱 최대값을 기준으로 Percentage 수정
  client/components/GameSlot/GameSlotContext.tsx
  client/components/GameSlot/index.tsx
  client/components/PercentageStatistics/index.tsx
  client/global.d.ts
Labels: FE

#263 ~23.03.24 작업사항
  client/components/GameSlot/GameSlotContext.tsx
  client/components/GameSlot/index.tsx
  client/components/Percentage/index.tsx
  client/components/PercentageStatistics/index.tsx
  client/global.d.ts
  client/pages/summoners/[summonerName].tsx
  client/utils/api.ts
  client/utils/matchStatistic.ts
  client/utils/time.ts
  server/src/matches/matches.service.ts
  server/src/matches/schemas/match.schema.ts
  server/src/matches/test/matches.service.spec.ts
  server/src/play/schemas/play.schema.ts
  server/src/summoners/schemas/summoner.schema.ts
  server/src/summoners/summoners.service.ts
  server/src/summoners/test/summoners.mock.ts
Labels: Bug, FE, BE

#270 hotfix: Summoner 업데이트 안되는 버그
  server/src/matches/matches.service.ts
Labels: Hotfix

#273 hotfix: 오타 수정 (Close #272)
  server/src/matches/matches.service.ts
Labels: Hotfix

#274 fix: 새로운 summoner 갱신 가능하게 변경
  client/global.d.ts
  server/src/matches/matches.service.ts
  server/src/summoners/schemas/summoner.schema.ts
  server/src/summoners/test/summoners.mock.ts
Labels: Bug, BE

#276 fix: polling시 중복 요청 방지
  client/pages/summoners/[summonerName].tsx
Labels: Bug, FE

#278 fix: 소환사 이름이 다른 소환사 이름에 포함되는 문제 해결
  server/src/summoners/summoners.service.ts
Labels: Bug, BE

#279 fix: 소환사가 없을 때 다시 검색이 되지 않는 문제 해결
  client/pages/summoners/[summonerName].tsx
Labels: Bug, FE

#277 fix: GameSlotDetail 레드팀 border-radius 설정
  client/components/GameSlot/style.ts
Labels: Bug, FE

#280 2023.03.25 작업사항
  client/components/GameSlot/style.ts
  client/global.d.ts
  client/pages/summoners/[summonerName].tsx
  server/src/matches/matches.service.ts
  server/src/summoners/schemas/summoner.schema.ts
  server/src/summoners/summoners.service.ts
  server/src/summoners/test/summoners.mock.ts
Labels: Bug, FE, BE

#283 이미지 lazyload animation
  client/components/ChallengeIcon/index.tsx
  client/components/ChampionPic/index.tsx
  client/components/GameSlot/index.tsx
  client/components/GameSlot/style.ts
  client/components/ItemIcon/index.tsx
  client/components/LazyImage/index.tsx
  client/components/RuneIcon/index.tsx
  client/components/SpellIcon/index.tsx
  client/components/SpellStrip/index.tsx
  client/components/SummonerProfilePic/index.tsx
Labels: FE

#282 FE: favicon 추가
  client/public/favicon.ico
Labels: FE, Chore

#287 FE footer 추가
  client/assets/github-mark.svg
  client/components/Footer/index.tsx
  client/pages/_app.tsx
  client/pages/index.tsx
Labels: FE

#289 FE 더보기/갱신 요청시 바로 UI에 적용 안되는 버그
  client/pages/summoners/[summonerName].tsx
Labels: Bug, FE

#290 Input bar 높이 iOS 대응
  client/components/SearchBar/style.ts
Labels: Bug, FE

#292 조회, 업데이트를 10 경기 단위로 수정
  server/src/matches/matches.service.ts
  server/src/play/play.service.ts
Labels: BE

#293 next/Image placeholder 사용
  client/components/ItemIcon/index.tsx
  client/components/LazyImage/index.tsx
Labels: FE

#294 ~23.03.29 작업사항
  client/assets/github-mark.svg
  client/components/ChallengeIcon/index.tsx
  client/components/ChampionPic/index.tsx
  client/components/Footer/index.tsx
  client/components/GameSlot/index.tsx
  client/components/GameSlot/style.ts
  client/components/ItemIcon/index.tsx
  client/components/LazyImage/index.tsx
  client/components/Logo/index.tsx
  client/components/RuneIcon/index.tsx
  client/components/SearchBar/style.ts
  client/components/SpellIcon/index.tsx
  client/components/SpellStrip/index.tsx
  client/components/SummonerProfilePic/index.tsx
  client/pages/_app.tsx
  client/pages/index.tsx
  client/pages/summoners/[summonerName].tsx
  client/public/favicon.ico
  server/src/matches/matches.service.ts
  server/src/play/play.service.ts
Labels: Bug, FE, BE, Refactor

#296 hotfix: spellStrip layout
  client/components/SpellStrip/index.tsx
Labels: FE, Hotfix

#302 Title 지정
  client/pages/_app.tsx
  client/pages/summoners/[summonerName].tsx
Labels: FE

#303 Google Analytics 추가
  client/.env.production
  client/lib/gtag.ts
  client/package.json
  client/pages/_document.tsx
  client/yarn.lock
Labels: FE

#306 Title 소환사 이름 버그 수정
  client/pages/summoners/[summonerName].tsx
Labels: Bug, FE
