Repository chococookie-lol/BARAM, pull requests merged in 2023-04, with the labels that each got.

#310 CI/CD 분리
  .github/workflows/client-ci.yml
  .github/workflows/deploy-client.yml
  .github/workflows/server-ci.yml
  .github/workflows/server-deploy.yml
  deploy-client.sh
  deploy-server.sh
  deploy.sh
Labels: Refactor, Chore

#313 소환사 이름 버그 수정 및 CI 개선
  .github/workflows/client-ci.yml
  .github/workflows/deploy-client.yml
  .github/workflows/server-ci.yml
  .github/workflows/server-deploy.yml
  client/pages/summoners/[summonerName].tsx
  deploy-client.sh
  deploy-server.sh
  deploy.sh
Labels: Bug, FE, Refactor

#312 소환사 정보가 갱신되지 않는 문제 수정
  server/src/matches/matches.module.ts
  server/src/matches/matches.service.ts
  server/src/matches/test/matches.service.spec.ts
  server/src/summoners/summoners.module.ts
Labels: Bug, BE

#314 소환사 정보가 갱신되지 않는 문제 수정
  server/src/matches/matches.module.ts
  server/src/matches/matches.service.ts
  server/src/matches/test/matches.service.spec.ts
  server/src/summoners/summoners.module.ts
Labels: Bug, BE

#315 FE: Percentage Bar 최대값 문제
  client/components/GameSlot/GameSlotContext.tsx
  client/components/GameSlot/index.tsx
  client/components/Percentage/index.tsx
  client/components/Percentage/style.ts
  client/components/PercentageStatistics/index.tsx
  client/global.d.ts
Labels: FE

#318 CI 캐싱 및 CD 수정
  .github/workflows/client-ci.yml
  .github/workflows/client-deploy.yml
  .github/workflows/server-ci.yml
  .github/workflows/server-deploy.yml
Labels: Chore

#320 🚑 hotfix: CI 오류 수정
  .github/workflows/client-ci.yml
  .github/workflows/server-ci.yml
Labels: Bug, Chore

#321 FE GameSlot에서 소환사 이름 클릭시 페이지 이동
  client/components/GameSlot/index.tsx
  client/components/GameSlot/style.ts
Labels: FE

#323 feat: DDragon 서버가 응답하지 않을 경우 처리
  client/pages/summoners/[summonerName].tsx
Labels: Bug, FE

#324 FE SEO meta 태그 설정
  client/.env.development
  client/.env.production
  client/package.json
  client/pages/_document.tsx
  client/pages/index.tsx
  client/pages/summoners/[summonerName].tsx
  client/public/BARAM.png
  client/yarn.lock
Labels: FE, Chore

#325 ~23.04.19 작업사항
  client/.env.development
  client/.env.production
  client/components/GameSlot/index.tsx
  client/components/GameSlot/style.ts
  client/package.json
  client/pages/_document.tsx
  client/pages/index.tsx
  client/pages/summoners/[summonerName].tsx
  client/public/BARAM.png
  client/yarn.lock
Labels: FE

#327 SEO 관련 추가 작업
  client/pages/index.tsx
  client/pages/summoners/[summonerName].tsx
  client/public/BARAM.png
Labels: FE, Chore

#328 최근 검색어, 즐겨찾기 기능 추가
  client/assets/star.svg
  client/assets/star_fill.svg
  client/components/SearchBar/index.tsx
  client/components/SearchBar/style.ts
  client/components/SearchPanel/index.tsx
  client/components/SearchPanel/style.ts
  client/global.d.ts
  client/pages/summoners/[summonerName].tsx
  client/utils/localStorage.ts
Labels: FE

#329 최근 검색어, 즐겨찾기 기능 추가
  client/assets/star.svg
  client/assets/star_fill.svg
  client/components/SearchBar/index.tsx
  client/components/SearchBar/style.ts
  client/components/SearchPanel/index.tsx
  client/components/SearchPanel/style.ts
  client/global.d.ts
  client/pages/index.tsx
  client/pages/summoners/[summonerName].tsx
  client/public/BARAM.png
  client/utils/localStorage.ts
Labels: FE
